//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mvc_comment
{
    using System;
    using System.Collections.Generic;
    
    public partial class commentTB
    {
        public int commntId { get; set; }
        public int commend_user_id { get; set; }
        public System.DateTime comment_date { get; set; }
        public string commnet_note { get; set; }
        public int comment_reply_id { get; set; }
        public int comment_excect_id { get; set; }
    }
}
